# Appendices 

## Code for removing the last 8 duplicates{#sec-duplicates}

We would like to use the `drop_duplicates` function, but to do so, we need to make sure that the label of the two duplicates are the same. Let's check if some sentence are the same with a concensus on the label: 


```python 
df_concensus = df_no_duplicates.groupby("sentence")["label_text"].agg(concensus = lambda X : len(set(X)) == 1)
print(df_concensus[df_concensus["concensus"] == False])
```

| sentence                                         |   concensus |
|:-------------------------------------------------|------------:|
| We need to get rid of fossil fuel subsidies now. |       False |

One sentence does not reach a concensus, We are going to remove it by hand and then use the `drop_duplicates` function: 

```python 
df_no_duplicates = df_no_duplicates.loc[
    df_no_duplicates["sentence"] != "We need to get rid of fossil fuel subsidies now.",
    :
]
df_no_duplicates = df_no_duplicates.drop_duplicates("sentence")
```

As a final check, we can use the Levenshtein distance to make sure that there are no lasting duplicates: 

```python
from Levenshtein import distance as lev_distance

threshold = 10

for i in range(len(df_no_duplicates)):
    for j in range(i + 1, len(df_no_duplicates)):
        s1 = df_no_duplicates.iloc[i]["sentence"]
        s2 = df_no_duplicates.iloc[j]["sentence"]
        d = lev_distance(s1, s2)
        if d < threshold:
            print(f"{d} : {s1} || {s2}")
```

With this loop, we have found 6 new sentences with duplicates:

- Global warming isn’t happening. || Global warming isn't happening.
- There is no solid evidence of global warming. || There is not solid evidence of global warming.
- Balance of evidence suggests a discernible human influence on global climate. || The balance of evidence suggests a discernible human influence on global climate.
- The alleged “ consensus ” behind the dangers of anthropogenic global warming is not nearly as settled among climate scientists as people imagine. || The alleged â consensus â behind the dangers of anthropogenic global warming is not nearly as settled among climate scientists as people imagine.
- Rising global temperatures during the 19th and 20th centuries may be linked to greater plant photosynthesis. || Rising global temperatures during the 19th and 20th centuries could be linked to greater plant photosynthesis.
- Climate change will continue to affect all types of weather phenomena and subsequently impact increasingly urbanised areas. || Climate change will continue to affect all types of weather phenomena and subsequently impact increasingly urbanized areas.

From there, one can choose to remove them or not. For this tutorial we will remove one of them if the two have the same label and remove both if they don't.

```python 
last_duplicates = [
    ("Global warming isn’t happening.","Global warming isn't happening."),
    ("There is no solid evidence of global warming.","There is not solid evidence of global warming."),
    ("Balance of evidence suggests a discernible human influence on global climate.","The balance of evidence suggests a discernible human influence on global climate."),
    ("The alleged “ consensus ” behind the dangers of anthropogenic global warming is not nearly as settled among climate scientists as people imagine.","The alleged â consensus â behind the dangers of anthropogenic global warming is not nearly as settled among climate scientists as people imagine."),
    ("Rising global temperatures during the 19th and 20th centuries may be linked to greater plant photosynthesis.","Rising global temperatures during the 19th and 20th centuries could be linked to greater plant photosynthesis."),
    ("Climate change will continue to affect all types of weather phenomena and subsequently impact increasingly urbanised areas.","Climate change will continue to affect all types of weather phenomena and subsequently impact increasingly urbanized areas."),
]

for (s1, s2) in last_duplicates:
    lab_s1 = df_no_duplicates.loc[df_no_duplicates["sentence"] == s1, "label_text"]
    lab_s2 = df_no_duplicates.loc[df_no_duplicates["sentence"] == s2, "label_text"]
    if lab_s1.item() == lab_s2.item() : 
        df_no_duplicates.drop(index = lab_s2.index)
    else: 
        df_no_duplicates.drop(index = [*lab_s1.index, *lab_s2.index])
```


## Good practices -> to move back to main 

**Stratification of the splits**  <!-- Move to good practices ??? -->

_The process of stratification consists of creating subgroups as defined by meta data (years for instance) and selecting a same number of texts per subgroup. This process intends to produce a dataset with uniform distribution across the selected metadata._

You dataset may contain additional variations through years, or sources. To make sure that these variations do not bias your model, you may want to stratify your splits according to said dimensions. If your dataset contains underrepresented labels, you can also choose to stratify your sets using the label column in order to create balanced splits which will contain as many texts per label.

In our case, we don't have additional metadata to stratify our splits with, also, the label distribution is not too unbalanced that we have to stratify the splits. We will not proceed to any stratification. 

If you were to do stratify your dataset, here is a code snippet to do it: 

```python
stratification_column = ["year"]
sub_groups = df.groupby(stratification_column, as_index = True)
samples_per_stratum = min(sub_groups.size())
df_stratified = (
    sub_groups
    .apply(lambda x : x.sample(n = samples_per_stratum))
    .reset_index()
    # .drop(["level_0", "level_1"], axis = 1) # Some additional columns will appear, you may want to drop them
)
```

## Understand the ins and outs of the pipeline{#sec-ins-and-outs}

To further understand the objects we manipulate, this section discusses the ins and outs of the tokenizer and the model.

From text entries we tokenize them as presented in [the tutorial](./index.qmd#sec-tokenization), and give them the right format and shape: 

```python  
entry = [
    "Hello World",
    "This is a second query"
]

tokenizer_parameters = {
    "truncation":True, 
    "padding":"max_length",
    "max_length":20 
}

model_input = tokenizer(entry,**tokenizer_parameters)
print(model_input["input_ids"])
print(model_input["attention_mask"])
```

```txt 
[[101, 7592, 2088, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2023, 2003, 1037, 2117, 23032, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
[[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
```

Models only accept Torch Tensors so we must convert them (as we did at the end of [formatting section](./index.qmd#sec-tokenization)). The model will only accept inputs of type integers: 

```python 
from torch import Tensor
model_input = {k:Tensor(v).to(dtype=int, device="cpu") for k,v in model_input.items()}
```

From there we can look at the base model (i.e. encoder model) output: 

```python 
base_model_output = model.to(device="cpu").base_model(**model_input)
base_model_output
```

```txt 
BaseModelOutputWithPoolingAndCrossAttentions(
  last_hidden_state=tensor([[[-0.2369,  ...,  0.5157],
    ...,
    [-0.5129, ..., 0.3993]],
  ],grad_fn=<NativeLayerNormBackward0>), 
  pooler_output=tensor([[-0.8752,  ...,  0.9330],
    [-0.7771, ..., 0.8831]],
    grad_fn=<TanhBackward0>), 
  hidden_states=None, 
  past_key_values=None, 
  attentions=None, 
  cross_attentions=None
)
```

The two outputs of interest are `last_hidden_state`and `pooler_output`. Note that the output depends on the model architecture. Most models will have an `last_hidden_state` but not all of them will have a `pooler_output`. Let's look at them: 

```python 
print("last_hidden_state")
print(base_model_output.last_hidden_state.shape)
print(base_model_output.last_hidden_state)
print("pooler_output")
print(base_model_output.pooler_output.shape)
print(base_model_output.pooler_output)
```

```txt
last_hidden_state
torch.Size([2, 20, 768])
tensor([[[-0.2369,  ...,  0.5157],
         ...,
         [-0.5129,  ...,  0.3993]],

        [[-0.1064,  ..., 1.1088],
         [-0.4536,  ..., 0.1622]]],
         ...,
       grad_fn=<NativeLayerNormBackward0>)
pooler_output
torch.Size([2, 768])
tensor([[-0.8752, -0.3879, -0.7193,  ...,  0.0322, -0.7454,  0.9330],
        [-0.7771, -0.4486, -0.8072,  ..., -0.6931, -0.7128,  0.8831]],
       grad_fn=<TanhBackward0>)
```

We can see that both outputs are matrices with values ranging between -1 and 1. The shapes differ however:

- `last_hidden_state` has a shape of `[2, 20, 768]` with `2` corresponding to the number of entries, `20` corresponds to the number of tokens per entry and `768` corresponds to the dimension of the embeddings[^embdeddings-dimension]. Therefore we understand that this correspond to a matrix mapping each entry and token to an embedding.
- `pooler_output` has a shape of `[2,768]`, we find again the `2` corresponding to the number of entries and `768` corresponding to the dimension of the embeddings. We understand that we lost the token dimension, which is the goal of `pooling` (more on [pooling](XXX)).

[^embdeddings-dimension]: Which matches the [description of the moel](./index.qmd#nte-model-description).

From there we can pass the output of the base model to the classifier:

```python 
model.classifier(base_model_output.pooler_output)
```

```txt 
tensor([[ 0.4330,  0.7812, -0.1392],
        [ 0.3477,  0.8166, -0.4157]], grad_fn=<AddmmBackward0>)
```

This time the classifier returns a matrix of shape `[2,3]`, `2` corresponding to the number of entries and `3` corresponding to the number of classes we set when loading the model.

If call the model directly we get: 

```python 
model(**model_input).logits
```

```python
SequenceClassifierOutput(
  loss=None, 
  logits=tensor([[ 0.5898,  0.6808, -0.2086],
        [ 0.3828,  1.1566, -0.0813]], grad_fn=<AddmmBackward0>), 
  hidden_states=None, 
  attentions=None
)
```

Here we see that the `logits` contains a $2\times 3$ matrix as well. The logits is the result of `model.classifier(base_model_output.pooler_output)` computed before, except the values aren't exact. This is norma as the model inherently rely on some randomized components.

To obtain probabilities over the 3 labels, one must use an [activation function](xxx), here we will use the `softmax` function because we are in a multiclass setting[^multilabel-activation]:

[^multilabel-activation]: For multilabel settings use the `sigmoid` function.

```python 
model.to(device="cpu")(**model_input).logits.softmax(1)
```

```txt 
tensor([[0.3401, 0.4815, 0.1785],
        [0.3526, 0.5000, 0.1474]], grad_fn=<SoftmaxBackward0>)

```

From there you can infer labels the way you want using the output probabilites. In the [evaluating section](./index.qmd#sec-evaluation), we assigned the label with the greater probability.

## Macro vs micro{#sec-macro-micro}